### ISSUE TITLE
Getting a error reading 'AuthHandler'

### ISSUE THREAD

**Issue by mikhail-karan** [nextauthjs/sveltekit-auth-example#3]
I get a error 500 page with the server error below after using both pnpm or yarn with the base scaffold project. 

Not able to get around this one. 

Tried both node version 16 and 18

Don't know if it helps but I'm on a M1 Macbook Pro

```
Cannot read properties of undefined (reading 'AuthHandler')
TypeError: Cannot read properties of undefined (reading 'AuthHandler')
    at Object.eval [as handle] (/node_modules/.pnpm/@auth+sveltekit@0.1.5_svelte@3.55.0/node_modules/@auth/sveltekit/index.js:37:19)
    at respond (file:///Users/mikhailkaran/Development/sveltekit-setup/node_modules/.pnpm/@sveltejs+kit@1.0.0_svelte@3.55.0+vite@4.0.1/node_modules/@sveltejs/kit/src/runtime/server/index.js:229:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///Users/mikhailkaran/Development/sveltekit-setup/node_modules/.pnpm/@sveltejs+kit@1.0.0_svelte@3.55.0+vite@4.0.1/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:444:22
```

**Comment by Spikeysanju** [comment]
@mikhail-karan I am experiencing the same issue.

**Comment by mikhail-karan** [comment]
This happens not only with this starter but with just following the documentation on a new sveltekit project.

**Comment by danielimmke** [comment]
Same - and the function signature for `AuthHandler` takes two arguments that aren't being passed in the example code and makes a call to /api/auth/session - which doesn't exist in SvelteKit.

I tried passing the Request that comes in as a prop from the load function on `+layout.server.ts` but I think the issue is deeper than that?

<img width="707" alt="image" src="https://user-images.githubusercontent.com/1744366/207778490-f746ad21-3a11-4876-afc3-0061c9ac26d3.png">

**Comment by pjlast** [comment]
Experiencing the same as well, also on an M1 Macbook for what it's worth.

**Comment by pjlast** [comment]
Okay it seems this is an issue with `@auth/sveltekit`'s dependency still being on `@auth/core` v0.1.3. If I manually update the `@auth/core` dependency of `@auth/sveltekit` in my `node_modules` folder to 0.1.4, then it seems to work.

**Comment by pjlast** [comment]
Looks like it just needs to be repackaged and republished to npm, which should fix it (running `pnpm pack` in the directory pins the core dependency correctly as 0.1.4)

**Comment by pjlast** [comment]
GitHub issue created here: https://github.com/nextauthjs/next-auth/issues/6068

**Comment by theetherGit** [comment]
I had the same issue on development server but when i made a build for it it gave me another other which was  
```bash
[next-auth][error][UNTRUST_HOST_ERROR] 
https://next-auth.js.org/errors#untrust_host_error Host must be trusted. URL was: http://192.168.2.101:4173/api/auth/session UntrustedHost: Host must be trusted. URL was: http://192.168.2.101:4173/api/auth/session
    at AuthHandler (file:///Users/shivammeena/WebstormProjects/SvelteKit-Auth-Example/node_modules/.pnpm/@auth+core@0.1.4/node_modules/@auth/core/index.js:204:23)
    at getSession (file:///Users/shivammeena/WebstormProjects/SvelteKit-Auth-Example/.svelte-kit/output/server/chunks/hooks.server.js:12:26)
    at Object.event.locals.getSession (file:///Users/shivammeena/WebstormProjects/SvelteKit-Auth-Example/.svelte-kit/output/server/chunks/hooks.server.js:35:39)
    at load (file:///Users/shivammeena/WebstormProjects/SvelteKit-Auth-Example/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:4:33)
    at load_server_data (file:///Users/shivammeena/WebstormProjects/SvelteKit-Auth-Example/.svelte-kit/output/server/chunks/index.js:946:42)
    at file:///Users/shivammeena/WebstormProjects/SvelteKit-Auth-Example/.svelte-kit/output/server/chunks/index.js:1935:24 {
  code: 'UNTRUST_HOST_ERROR'
}
Error: There is a problem with the server configuration. Check the server logs for more information.
    at getSession (file:///Users/shivammeena/WebstormProjects/SvelteKit-Auth-Example/.svelte-kit/output/server/chunks/hooks.server.js:19:9)
    at async load (file:///Users/shivammeena/WebstormProjects/SvelteKit-Auth-Example/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:4:14)
    at async load_server_data (file:///Users/shivammeena/WebstormProjects/SvelteKit-Auth-Example/.svelte-kit/output/server/chunks/index.js:946:18)
    at async file:///Users/shivammeena/WebstormProjects/SvelteKit-Auth-Example/.svelte-kit/output/server/chunks/index.js:1935:18
```

When i looked more into it i found this piece of code 
```javascript
function SvelteKitAuth(options) {
  const { prefix = "/auth", ...authOptions } = options;
  authOptions.secret ??= AUTH_SECRET;
  authOptions.trustHost ??= !!(env.AUTH_TRUST_HOST ?? env.VERCEL ?? dev);
  return SvelteKitAuthHandler(prefix, authOptions);
}
```
Here we can see  ` authOptions.trustHost ??= !!(env.AUTH_TRUST_HOST ?? env.VERCEL ?? dev);`  which is looking for `AUTH_TRUST_HOST` in env so we need to add this in our `.env` file. then you can make a build it will work.

**Comment by balazsorban44** [comment]
Thanks, please reopen in the main repo https://github.com/nextauthjs/next-auth
